
export const Language = {
  unk: { label: 'Unknown', value: 'unk' },
  eng: { label: 'English', value: 'eng' },
  spa: { label: 'Spanish', value: 'spa' },
  aar: { label: 'Afar', value: 'aar' },
  abk: { label: 'Abkhaz', value: 'abk' },
  afr: { label: 'Afrikaans', value: 'afr' },
  aka: { label: 'Akan', value: 'aka' },
  amh: { label: 'Amharic', value: 'amh' },
  ara: { label: 'Arabic', value: 'ara' },
  arg: { label: 'Aragonese', value: 'arg' },
  asm: { label: 'Assamese', value: 'asm' },
  ava: { label: 'Avaric', value: 'ava' },
  aym: { label: 'Aymara', value: 'aym' },
  aze: { label: 'Azerbaijani', value: 'aze' },
  bak: { label: 'Bashkir', value: 'bak' },
  bam: { label: 'Bambara', value: 'bam' },
  bel: { label: 'Belarusian', value: 'bel' },
  ben: { label: 'Bengali (Bangla)', value: 'ben' },
  bih: { label: 'Bihari', value: 'bih' },
  bis: { label: 'Bislama', value: 'bis' },
  bod: { label: 'Tibetan', value: 'bod' },
  bos: { label: 'Bosnian', value: 'bos' },
  bre: { label: 'Breton', value: 'bre' },
  bul: { label: 'Bulgarian', value: 'bul' },
  cal: { label: 'Carolinian', value: 'cal' },
  cat: { label: 'Catalan (Valencian)', value: 'cat' },
  ces: { label: 'Czech', value: 'ces' },
  cha: { label: 'Chamorro', value: 'cha' },
  che: { label: 'Chechen', value: 'che' },
  chv: { label: 'Chuvash', value: 'chv' },
  cmn: { label: 'Chinese (Mandarin)', value: 'cmn' },
  cos: { label: 'Corsican', value: 'cos' },
  cre: { label: 'Cree', value: 'cre' },
  crp: { label: 'Creole/Pidgin', value: 'crp' },
  cym: { label: 'Welsh', value: 'cym' },
  dan: { label: 'Danish', value: 'dan' },
  deu: { label: 'German', value: 'deu' },
  div: { label: 'Divehi/Dhivehi/Maldivian', value: 'div' },
  dzo: { label: 'Dzongkha', value: 'dzo' },
  ell: { label: 'Greek', value: 'ell' },
  est: { label: 'Estonian', value: 'est' },
  eus: { label: 'Basque', value: 'eus' },
  ewe: { label: 'Ewe', value: 'ewe' },
  fao: { label: 'Faroese', value: 'fao' },
  fas: { label: 'Persian (Farsi)', value: 'fas' },
  fij: { label: 'Fijian', value: 'fij' },
  fin: { label: 'Finnish', value: 'fin' },
  fra: { label: 'French', value: 'fra' },
  fry: { label: 'Western Frisian', value: 'fry' },
  ful: { label: 'Fula/Fulah (Pulaar/Pular)', value: 'ful' },
  gaa: { label: 'Ga', value: 'gaa' },
  gla: { label: 'Scottish Gaelic', value: 'gla' },
  gle: { label: 'Irish', value: 'gle' },
  glg: { label: 'Galician', value: 'glg' },
  glv: { label: 'Manx', value: 'glv' },
  grn: { label: 'Guaraní', value: 'grn' },
  guj: { label: 'Gujarati', value: 'guj' },
  hat: { label: 'Haitian', value: 'hat' },
  hau: { label: 'Hausa', value: 'hau' },
  heb: { label: 'Hebrew', value: 'heb' },
  her: { label: 'Herero', value: 'her' },
  hin: { label: 'Hindi', value: 'hin' },
  hmn: { label: 'Hmong', value: 'hmn' },
  hmo: { label: 'Hiri Motu', value: 'hmo' },
  hrv: { label: 'Croatian', value: 'hrv' },
  hun: { label: 'Hungarian', value: 'hun' },
  hye: { label: 'Armenian', value: 'hye' },
  ibo: { label: 'Igbo', value: 'ibo' },
  iii: { label: 'Nuosu', value: 'iii' },
  iku: { label: 'Inuktitut', value: 'iku' },
  ind: { label: 'Indonesian', value: 'ind' },
  ipk: { label: 'Inupiaq', value: 'ipk' },
  isl: { label: 'Icelandic', value: 'isl' },
  ita: { label: 'Italian', value: 'ita' },
  jav: { label: 'Javanese', value: 'jav' },
  jpn: { label: 'Japanese', value: 'jpn' },
  kal: { label: 'Kalaallisut (Greenlandic)', value: 'kal' },
  kan: { label: 'Kannada', value: 'kan' },
  kar: { label: 'Karen', value: 'kar' },
  kas: { label: 'Kashmiri', value: 'kas' },
  kat: { label: 'Georgian', value: 'kat' },
  kau: { label: 'Kanuri', value: 'kau' },
  kaz: { label: 'Kazakh', value: 'kaz' },
  khm: { label: 'Khmer', value: 'khm' },
  kik: { label: 'Kikuyu/Gikuyu', value: 'kik' },
  kin: { label: 'Kinyarwanda', value: 'kin' },
  kir: { label: 'Kyrgyz', value: 'kir' },
  kom: { label: 'Komi', value: 'kom' },
  kon: { label: 'Kongo', value: 'kon' },
  kor: { label: 'Korean', value: 'kor' },
  kua: { label: 'Kwanyama/Kuanyama', value: 'kua' },
  kur: { label: 'Kurdish', value: 'kur' },
  lao: { label: 'Lao', value: 'lao' },
  lat: { label: 'Latin', value: 'lat' },
  lav: { label: 'Latvian', value: 'lav' },
  lin: { label: 'Lingala', value: 'lin' },
  lit: { label: 'Lithuanian', value: 'lit' },
  lub: { label: 'Luba-Katanga', value: 'lub' },
  lug: { label: 'Ganda', value: 'lug' },
  mah: { label: 'Marshallese', value: 'mah' },
  mal: { label: 'Malayalam', value: 'mal' },
  mar: { label: 'Marathi/Marāṭhī', value: 'mar' },
  mkd: { label: 'Macedonian', value: 'mkd' },
  mlg: { label: 'Malagasy', value: 'mlg' },
  mlt: { label: 'Maltese', value: 'mlt' },
  mnk: { label: 'Mandinka', value: 'mnk' },
  mnw: { label: 'Mon', value: 'mnw' },
  mon: { label: 'Mongolian', value: 'mon' },
  mri: { label: 'Māori', value: 'mri' },
  msa: { label: 'Malay', value: 'msa' },
  mya: { label: 'Burmese', value: 'mya' },
  nau: { label: 'Nauru', value: 'nau' },
  nav: { label: 'Navajo/Navaho', value: 'nav' },
  nbl: { label: 'South Ndebele', value: 'nbl' },
  nde: { label: 'North Ndebele', value: 'nde' },
  ndo: { label: 'Ndonga', value: 'ndo' },
  nep: { label: 'Nepali', value: 'nep' },
  nld: { label: 'Dutch', value: 'nld' },
  nno: { label: 'Norwegian Nynorsk', value: 'nno' },
  nob: { label: 'Norwegian Bokmål', value: 'nob' },
  nya: { label: 'Chichewa/Chewa/Nyanja', value: 'nya' },
  oci: { label: 'Occitan', value: 'oci' },
  oji: { label: 'Ojibwe/Ojibwa', value: 'oji' },
  ori: { label: 'Oriya', value: 'ori' },
  orm: { label: 'Oromo', value: 'orm' },
  oss: { label: 'Ossetian/Ossetic', value: 'oss' },
  pan: { label: 'Panjabi/Punjabi', value: 'pan' },
  pol: { label: 'Polish', value: 'pol' },
  por: { label: 'Portuguese', value: 'por' },
  pus: { label: 'Pashto/Pushto', value: 'pus' },
  que: { label: 'Quechua', value: 'que' },
  roh: { label: 'Romansh', value: 'roh' },
  ron: { label: 'Romanian', value: 'ron' },
  run: { label: 'Kirundi', value: 'run' },
  rus: { label: 'Russian', value: 'rus' },
  sag: { label: 'Sango', value: 'sag' },
  sin: { label: 'Sinhala (Sinhalese)', value: 'sin' },
  slk: { label: 'Slovak', value: 'slk' },
  slv: { label: 'Slovene', value: 'slv' },
  sme: { label: 'Northern Sami', value: 'sme' },
  smo: { label: 'Samoan', value: 'smo' },
  sna: { label: 'Shona', value: 'sna' },
  snd: { label: 'Sindhi', value: 'snd' },
  som: { label: 'Somali', value: 'som' },
  sot: { label: 'Southern Sotho', value: 'sot' },
  sqi: { label: 'Albanian', value: 'sqi' },
  srd: { label: 'Sardinian', value: 'srd' },
  srp: { label: 'Serbian', value: 'srp' },
  ssw: { label: 'Swati', value: 'ssw' },
  sun: { label: 'Sundanese', value: 'sun' },
  swa: { label: 'Swahili', value: 'swa' },
  swe: { label: 'Swedish', value: 'swe' },
  tah: { label: 'Tahitian', value: 'tah' },
  tam: { label: 'Tamil', value: 'tam' },
  tat: { label: 'Tatar', value: 'tat' },
  tel: { label: 'Telugu', value: 'tel' },
  tgk: { label: 'Tajik', value: 'tgk' },
  tgl: { label: 'Tagalog', value: 'tgl' },
  tha: { label: 'Thai', value: 'tha' },
  tir: { label: 'Tigrinya', value: 'tir' },
  ton: { label: 'Tonga', value: 'ton' },
  tsn: { label: 'Tswana', value: 'tsn' },
  tso: { label: 'Tsonga', value: 'tso' },
  tuk: { label: 'Turkmen', value: 'tuk' },
  tur: { label: 'Turkish', value: 'tur' },
  twi: { label: 'Twi', value: 'twi' },
  uig: { label: 'Uyghur/Uighur', value: 'uig' },
  ukr: { label: 'Ukrainian', value: 'ukr' },
  urd: { label: 'Urdu', value: 'urd' },
  uzb: { label: 'Uzbek', value: 'uzb' },
  ven: { label: 'Venda', value: 'ven' },
  vie: { label: 'Vietnamese', value: 'vie' },
  wln: { label: 'Walloon', value: 'wln' },
  wol: { label: 'Wolof', value: 'wol' },
  xho: { label: 'Xhosa', value: 'xho' },
  yue: { label: 'Chinese (Cantonese)', value: 'yue' },
  yid: { label: 'Yiddish', value: 'yid' },
  yor: { label: 'Yoruba', value: 'yor' },
  zha: { label: 'Zhuang / Chuang', value: 'zha' },
  zho: { label: 'Chinese (Other/Unknown)', value: 'zho' },
  zul: { label: 'Zulu', value: 'zul' }
};
